<?php require_once "templates/head.phtml";
    require_once "templates/header.phtml";
?>


<form action="adddirectores" method="POST">
    <input type="text" name="director" placeholder="director nuevo">
    <input type="text" name="apellido" placeholder="apellido nuevo">
    <input type="text" name="edad" placeholder="edad ">
    <input type="number" name="premios" placeholder="premios">
    <input type="number" name="mayorexito" placeholder="Mayor exito">
    <button type="submit" name='name'>ADD</button>
</form>

