<?php require_once "templates/head.phtml";
    require_once "templates/header.phtml";
?>


<form action="adddirectores" method="POST">
    <input type="text" name="director" placeholder="director nuevo" class="form-control">
    <input type="text" name="apellido" placeholder="apellido nuevo" class="form-control">
    <input type="text" name="edad" placeholder="edad " class="form-control">
    <input type="number" name="premios" placeholder="premios" class="form-control">
    <input type="number" name="mayorexito" placeholder="Mayor exito" class="form-control">
    <button type="submit" name='name'>ADD</button>
</form>

