<?php require_once "templates/head.phtml";
    require_once "templates/header.phtml";
?>


<form action="addpelicula" method="POST">
    <input type="text" name="nombre" placeholder="nombre nuevo" class="form-control">
    <input type="text" name="descripcion" placeholder="descripcion nuevo" class="form-control">
    <input type="text" name="genero" placeholder="genero nuevo" class="form-control">
    <input type="number" name="edad" placeholder="clasificacion de edad nueva" class="form-control">
    
    <select name="director" >
        <?php foreach ($directores as $d) { ?>
    <option value="<?= $d->id_director?>"><?= $d->Director?></option> 
        <?php } ?>
    </select>
    <button type="submit" name='name'>ADD</button>
</form>

