<?php require_once "templates/head.phtml";?>
<?php require_once "templates/header.phtml";?>

    <nav>
        <form action="router.php">
            <ul>
                <?php foreach($directores as $director){ ?>
                    <li><a href="peliculasDeEstosDirectores/<?=$director->id_director?>"><?= $director->Director ?>, <?= $director->Apellido ?></a></li>
                    
                <?php }?>   
                
            </ul>
        </form> 
        
    </nav>    

   