<?php require_once "templates/head.phtml";?>
<?php require_once "templates/header.phtml";?>

    <nav>
            <ul>

        <?php if(isset($_SESSION["IS_LOGGED"]) && $_SESSION["IS_LOGGED"] == true){?>
        
        <form action="muestraadddirectores" method="POST">
            <button type="submit" >AGREGAR</button>
        </form> 
        <?php
                }
                foreach($directores as $director){ ?>
                    <li><a href="peliculasDeEstosDirectores/<?=$director->id_director?>"><?= $director->Director ?>, <?= $director->Apellido ?></a></li>
                    <?php if(isset($_SESSION["IS_LOGGED"]) && $_SESSION["IS_LOGGED"] == true){?>

                    <form action="eliminadirector/<?=$director->id_director ?>">
                        <button type="submit">ELIMINAR</button>
                    </form>

                    <form action="editardirector/<?=$director->id_director ?>">
                        <button type="submit">EDITAR</button>
                    </form>
                    
                <?php }?>
                <?php }?>   
                
            </ul>
        </form> 
        
    </nav>    