<?php require_once "templates/head.phtml";?>
<?php require_once "templates/header.phtml";?>

    <nav>
        <form action="router.php">
            <ul>
                <?php foreach($directores as $director){ ?>
                    <li><a href="peliculasDeEstosDirectores/<?=$director->id_director?>"><?= $director->Director ?>, <?= $director->Apellido ?></a></li>
                    <?php if(isset($_SESSION["IS_LOGGED"]) && $_SESSION["IS_LOGGED"] == true){?>
                    <form action="eliminadirector"  method="POST">
                        <button type="submit" name="eliminar" >ELIMINAR</button>
                    </form>
                    <form action="editarpelicula" method="POST">
                        <button type="submit" name="ID" >EDITAR</button>
                    </form>
                <?php }?>
                <?php }?>   
                
            </ul>
        </form> 
        
    </nav>    