<?php require_once "templates/head.phtml"; ?>
<header>
    <h1>PELISplus</h1>
    <nav>
        <form action="router.php">
            <ul>
            <?php echo($_SESSION['USER_ID'])?>
                <?php if (!isset($_SESSION['USER_ID'])) : ?>
                    <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="login">Login</a>
                    </li>
                <?php else : ?>
                    <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="logout">Logout (<?php echo $_SESSION['USER_NAME'] ?>)</a>
                <?php endif; ?>
                    </li>
                <li>
                    <a href="directores">Directores</a>
                </li>
                <li>
                <a href="home">Peliculas</a>
                </li>

            </ul>
        </form>
    </nav>

</header>