<?php require_once "templates/head.phtml"; ?>
<header>
    <h1>PELISplus</h1>


    <?php if (!isset($_SESSION['USER_ID'])) : ?>
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="login">Login</a>
        </li>
    <?php else : ?>
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="logout">Logout (<?= $_SESSION['USER_NAME'] ?>)</a>
        </li>
    <?php endif ?>


</header>