<?php require_once "templates/header.phtml";?>

<section>
    <form action="router.php" method="post">
        <input type="text" name="NomubreUser" placeholder="nombre de usuario">
        <input type="text" name="Password" placeholder="password">
        <input type="text" name="Password2" placeholder="repita password">
        
        <button type="submit" name="submit">Login</button>
        
        <button type="submit" name="submit">USER CASUAL</button>
        
        <?if($_POST['password'] == $_POST['password2']){?>
            <div><h4>La contraseña es erronea</h4></div>
        <?}?>
    </form>

</section>

<?php require_once "templates/footer.phtml"?>