<?php require_once "templates/head.phtml";?>
<?php require_once "templates/header.phtml";?>

<section>
    <form method="POST" action="validacion">
        <input type="text" name="usuario" placeholder="nombre de usuario">
        <input type="text" name="contrasenia" placeholder="password">
       
        
        
        <?php if ($error) { ?>
            <div class="alert alert-danger mt-3">
                <?php echo $error; ?>
                
            </div>
            <?php }?>
            <button type="submit" >Login</button>
        </form>
</section>

<?php require_once "templates/footer.phtml"?>