<?php require_once "templates/header.phtml";?>
<head></head>
<section>
    <form action="router.php" method="post">
        <input type="text" name="NomubreUser" placeholder="nombre de usuario">
        <input type="text" name="Password" placeholder="password">
       
        
        <button type="submit" name="submit">Login</button>
        
        <button type="submit" name="submit">USER CASUAL</button>
        
      
    </form>

</section>

<?php require_once "templates/footer.phtml"?>