<?php require_once "templates/head.phtml";?>
<?php require_once "templates/header.phtml";?>


<section>

    <h2>Lista de peliculas</h2>
    <ul>
    <?php if(isset($_SESSION["IS_LOGGED"]) && $_SESSION["IS_LOGGED"] == true){?>
        <form action="muestraaddpelicula" method="POST">
            <button type="submit" >AGREGAR</button>
        </form>
        <?php 
        }
        foreach($peliculas as $pelicula){?>
            <li>
                <a href="detallesPelicula/<?=$pelicula->ID?>"><?=$pelicula->Nombre?></a> 
                <?php if(isset($_SESSION["IS_LOGGED"]) && $_SESSION["IS_LOGGED"] == true){?>
                    
                    <form action="eliminapelicula/<?=$pelicula->ID?>">
                        <button type="submit">ELIMINAR</button>
                    </form>
                    
                    <form action="editarpelicula/<?=$pelicula->ID?>" method="post">
                        <button type="submit">EDITAR</button>
                    </form>
                    
                <?php }?>
            </li>
        <?php }?>
    </ul>
</section>