<?php require_once "templates/head.phtml";?>
<?php require_once "templates/header.phtml";?>


<section>

    <h2>Lista de peliculas</h2>
    <ul>
        <form action="agregarpelicula" method="POST">
            <button type="submit" href="">AGREGAR</button>
        </form>
        <?php foreach($peliculas as $pelicula){?>
            <li>
                <a href="detallesPelicula/<?=$pelicula->ID?>"><?=$pelicula->Nombre?></a> 
                <?php if(isset($_SESSION["IS_LOGGED"]) && $_SESSION["IS_LOGGED"] == true){?>
                    <a href="eliminapelicula/<?=$pelicula->ID?>">ELIMINAR</a> 
                    <a href="editarpelicula/<?=$pelicula->ID?>">EDITAR</a> 
                <?php }?>
            </li>
        <?php }?>
    </ul>
</section>