<?php require_once "templates/head.phtml";?>

<?php
require_once 'templates/header.phtml';
?>
<form action="updateDirectores/<?= $id ?>" method="post">
    <input type="text" name="director" placeholder="director nuevo" class="form-control">
    <input type="text" name="apellido" placeholder="apellido nuevo" class="form-control">
    <input type="number" name="edad" placeholder="edad nueva" class="form-control">
    <input type="number" name="premios" placeholder="premios nuevo" class="form-control">
    <input type="numbre" name="mayorExito" placeholder="mayoerExito nueva" class="form-control">
    <button type="submit" name = "id" >ADD</button>
</form>